In [2]:
!pip -q install feast==0.64.0 pyarrow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 20.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 17.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 17.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 45.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 66.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 30.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 4.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.4.0 requires tenacity<10,>=9, but you have tenacity 8.5.0 which is incompatible.

In [3]:
import feast

print("Feast version:", feast.__version__)

Feast version: 0.64.0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [5]:
from google.colab import files

uploaded = files.upload()

Saving Curriculum_Industry_Skill_Alignment.csv to Curriculum_Industry_Skill_Alignment (1).csv

In [7]:
import pandas as pd

df = pd.read_csv("Curriculum_Industry_Skill_Alignment (1).csv")

print(df.head())
print(df.shape)

  Student_ID  Gender  Semester  CGPA  Programming  DSA  DBMS  OS  CN  OOP  \
0       S001  Female         7  8.43            3    7     6   6   5    4
1       S002  Female         7  8.88            5    9     8   7   5    6
2       S003    Male         7  8.68            3    6     7   4   6    4
3       S004    Male         8  7.76            7    6     8   3   6    3
4       S005    Male         8  8.84            9    9     8   6   5   10

   ...  AI_ML  Communication  Aptitude  Teamwork  Problem_Solving  Internship  \
0  ...      6              6         3         6                9         Yes
1  ...      8              8         7         3               10         Yes
2  ...      8              8         6         7                4         Yes
3  ...      8              6        10         9               10         Yes
4  ...      9              4         9         9               10          No

   Certifications  Projects_Completed  Placement_Status  Industry_Readiness
0               3                   5        Not Placed           Not Ready
1               3                   1            Placed               Ready
2               4                   6        Not Placed           Not Ready
3               2                   2        Not Placed           Not Ready
4               4                   1        Not Placed           Not Ready

[5 rows x 25 columns]
(100, 25)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [8]:
print(df.columns)
print(df.info())
print(df.isnull().sum())

Index(['Student_ID', 'Gender', 'Semester', 'CGPA', 'Programming', 'DSA',
       'DBMS', 'OS', 'CN', 'OOP', 'Python', 'Java', 'SQL', 'Web_Development',
       'Cloud', 'AI_ML', 'Communication', 'Aptitude', 'Teamwork',
       'Problem_Solving', 'Internship', 'Certifications', 'Projects_Completed',
       'Placement_Status', 'Industry_Readiness'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          100 non-null    object
 1   Gender              100 non-null    object
 2   Semester            100 non-null    int64
 3   CGPA                100 non-null    float64
 4   Programming         100 non-null    int64
 5   DSA                 100 non-null    int64
 6   DBMS                100 non-null    int64
 7   OS                  100 non-null    int64
 8   CN                  100 non-null    int64
 9   OOP                 100 non-null    int64
 10  Python              100 non-null    int64
 11  Java                100 non-null    int64
 12  SQL                 100 non-null    int64
 13  Web_Development     100 non-null    int64
 14  Cloud               100 non-null    int64
 15  AI_ML               100 non-null    int64
 16  Communication       100 non-null    int64
 17  Aptitude            100 non-null    int64
 18  Teamwork            100 non-null    int64
 19  Problem_Solving     100 non-null    int64
 20  Internship          100 non-null    object
 21  Certifications      100 non-null    int64
 22  Projects_Completed  100 non-null    int64
 23  Placement_Status    100 non-null    object
 24  Industry_Readiness  100 non-null    object
dtypes: float64(1), int64(19), object(5)
memory usage: 19.7+ KB
None
Student_ID            0
Gender                0
Semester              0
CGPA                  0
Programming           0
DSA                   0
DBMS                  0
OS                    0
CN                    0
OOP                   0
Python                0
Java                  0
SQL                   0
Web_Development       0
Cloud                 0
AI_ML                 0
Communication         0
Aptitude              0
Teamwork              0
Problem_Solving       0
Internship            0
Certifications        0
Projects_Completed    0
Placement_Status      0
Industry_Readiness    0
dtype: int64

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [10]:
import pandas as pd


df["student_id"] = df["Student_ID"].str.replace("S", "").astype("int64")



df["CGPA"] = df["CGPA"].fillna(df["CGPA"].median())
df["Projects_Completed"] = df["Projects_Completed"].fillna(df["Projects_Completed"].median())



df["gender_encoded"] = df["Gender"].map({
    "Male": 0,
    "Female": 1
}).astype("int64")



df["skill_count"] = (
    (df["Programming"] > 5).astype(int) +
    (df["DSA"] > 5).astype(int) +
    (df["DBMS"] > 5).astype(int) +
    (df["OS"] > 5).astype(int) +
    (df["CN"] > 5).astype(int) +
    (df["OOP"] > 5).astype(int)
).astype("int64")



df["is_placed"] = (
    df["Placement_Status"] == "Placed"
).astype("int64")



df["semester"] = df["Semester"].astype("int64")
df["cgpa"] = df["CGPA"].astype("float32")
df["programming"] = df["Programming"].astype("float32")


df["industry_readiness"] = df["Industry_Readiness"].map({
    "Not Ready": 0,
    "Ready": 1
}).astype("int64")

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [11]:
df[
    [
        "student_id",
        "semester",
        "gender_encoded",
        "cgpa",
        "programming",
        "skill_count",
        "is_placed",
        "industry_readiness"
    ]
].head()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,semester,gender_encoded,cgpa,programming,skill_count,is_placed,industry_readiness
0,1,7,1,8.43,3.0,3,0,0
1,2,7,1,8.88,5.0,4,1,1
2,3,7,0,8.68,3.0,3,0,0
3,4,8,0,7.76,7.0,4,0,0
4,5,8,0,8.84,9.0,5,0,0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [12]:
base_time = pd.Timestamp(
    "2025-01-01",
    tz="UTC"
)


df["event_timestamp"] = (
    base_time +
    pd.to_timedelta(
        df["student_id"],
        unit="s"
    )
)


df["created_timestamp"] = (
    df["event_timestamp"] +
    pd.Timedelta(seconds=1)
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [13]:
feature_df = df[
    [
        "student_id",
        "event_timestamp",
        "created_timestamp",
        "semester",
        "gender_encoded",
        "cgpa",
        "programming",
        "skill_count",
        "is_placed"
    ]
].copy()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [14]:
label_df = df[
    [
        "student_id",
        "event_timestamp",
        "industry_readiness"
    ]
].copy()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [15]:
print("Feature data:")
display(feature_df.head())


print("Labels:")
display(label_df.head())

Feature data:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,event_timestamp,created_timestamp,semester,gender_encoded,cgpa,programming,skill_count,is_placed
0,1,2025-01-01 00:00:01+00:00,2025-01-01 00:00:02+00:00,7,1,8.43,3.0,3,0
1,2,2025-01-01 00:00:02+00:00,2025-01-01 00:00:03+00:00,7,1,8.88,5.0,4,1
2,3,2025-01-01 00:00:03+00:00,2025-01-01 00:00:04+00:00,7,0,8.68,3.0,3,0
3,4,2025-01-01 00:00:04+00:00,2025-01-01 00:00:05+00:00,8,0,7.76,7.0,4,0
4,5,2025-01-01 00:00:05+00:00,2025-01-01 00:00:06+00:00,8,0,8.84,9.0,5,0

Labels:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

   student_id           event_timestamp  industry_readiness
0           1 2025-01-01 00:00:01+00:00                   0
1           2 2025-01-01 00:00:02+00:00                   1
2           3 2025-01-01 00:00:03+00:00                   0
3           4 2025-01-01 00:00:04+00:00                   0
4           5 2025-01-01 00:00:05+00:00                   0

In [16]:
import os


repo_path = "/content/curriculum_industry_skill_alignment"


os.makedirs(
    f"{repo_path}/data",
    exist_ok=True
)

In [17]:
import os


repo_path = "/content/curriculum_industry_skill_alignment"


os.makedirs(
    f"{repo_path}/data",
    exist_ok=True
)

In [18]:
feature_df.to_parquet(
    f"{repo_path}/data/curriculum_features.parquet",
    index=False
)

In [19]:
feature_store_yaml = """
project: curriculum_industry_skill_alignment


registry: data/registry.db


provider: local


offline_store:
  type: file


online_store:
  type: sqlite
  path: data/online_store.db
"""


with open(
    f"{repo_path}/feature_store.yaml",
    "w"
) as f:
    f.write(feature_store_yaml)

In [20]:
feature_definition = '''
from datetime import timedelta

from feast import (
    Entity,
    FeatureView,
    FeatureService,
    Field,
    FileSource
)

from feast.types import (
    Float32,
    Int64
)

# -----------------------------
# ENTITY
# -----------------------------

student = Entity(
    name="student",
    join_keys=["student_id"],
    description="CSE student"
)

# -----------------------------
# DATA SOURCE
# -----------------------------

curriculum_source = FileSource(
    name="curriculum_source",
    path="data/curriculum_features.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp"
)

# -----------------------------
# FEATURE VIEW
# -----------------------------

curriculum_feature_view = FeatureView(
    name="curriculum_features",
    entities=[student],

    ttl=timedelta(days=50000),

    schema=[
        Field(name="semester", dtype=Int64),
        Field(name="gender_encoded", dtype=Int64),
        Field(name="cgpa", dtype=Float32),
        Field(name="programming", dtype=Float32),
        Field(name="skill_count", dtype=Int64),
        Field(name="is_placed", dtype=Int64),
    ],

    source=curriculum_source,

    online=True
)

# -----------------------------
# FEATURE SERVICE
# -----------------------------

curriculum_feature_service = FeatureService(
    name="industry_readiness_service",
    features=[
        curriculum_feature_view
    ]
)
'''

with open(
    f"{repo_path}/features.py",
    "w"
) as f:
    f.write(feature_definition)

In [21]:
!find /content/curriculum_industry_skill_alignment -maxdepth 2 -type f

/content/curriculum_industry_skill_alignment/data/curriculum_features.parquet
/content/curriculum_industry_skill_alignment/features.py
/content/curriculum_industry_skill_alignment/feature_store.yaml

In [22]:
%cd /content/curriculum_industry_skill_alignment

/content/curriculum_industry_skill_alignment

In [23]:
!feast apply

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/content/curriculum_industry_skill_alignment/features.py:21: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'student'.
  student = Entity(
No project found in the repository. Using project name curriculum_industry_skill_alignment defined in feature_store.yaml
Applying changes for project curriculum_industry_skill_alignment
Created project curriculum_industry_skill_alignment
Created entity student
Created feature view curriculum_features
Created feature service industry_readiness_service

Created sqlite table curriculum_industry_skill_alignment_curriculum_features

In [24]:
!feast entities list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME     DESCRIPTION    TYPE
student  CSE student    ValueType.UNKNOWN

In [25]:
!feast feature-views list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME                 ENTITIES     TYPE         ENABLED    STATE
curriculum_features  {'student'}  FeatureView  Yes        STATE_UNSPECIFIED

In [26]:
from feast import FeatureStore


store = FeatureStore(
    repo_path="/content/curriculum_industry_skill_alignment"
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [27]:
feature_service = store.get_feature_service(
    "industry_readiness_service"
)

In [28]:
  entity_df = label_df.copy()

display(entity_df.head())

   student_id           event_timestamp  industry_readiness
0           1 2025-01-01 00:00:01+00:00                   0
1           2 2025-01-01 00:00:02+00:00                   1
2           3 2025-01-01 00:00:03+00:00                   0
3           4 2025-01-01 00:00:04+00:00                   0
4           5 2025-01-01 00:00:05+00:00                   0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [29]:
training_data = store.get_historical_features(
    entity_df=entity_df,
    features=feature_service
).to_df()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [30]:
display(training_data.head())

,student_id,event_timestamp,industry_readiness,semester,gender_encoded,cgpa,programming,skill_count,is_placed
0,1,2025-01-01 00:00:01+00:00,0,7,1,8.43,3.0,3,0
1,2,2025-01-01 00:00:02+00:00,1,7,1,8.88,5.0,4,1
2,3,2025-01-01 00:00:03+00:00,0,7,0,8.68,3.0,3,0
3,4,2025-01-01 00:00:04+00:00,0,8,0,7.76,7.0,4,0
4,5,2025-01-01 00:00:05+00:00,0,8,0,8.84,9.0,5,0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [56]:
feature_columns = [
    "semester",
    "gender_encoded",
    "cgpa",
    "programming"
]

In [57]:
X = training_data[feature_columns]

y = training_data["industry_readiness"]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [58]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [59]:
model = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

In [60]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(
    max_depth=1,
    min_samples_split=15,
    min_samples_leaf=8,
    random_state=42
)

model.fit(
    X_train,
    y_train
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

DecisionTreeClassifier(max_depth=1, min_samples_leaf=8, min_samples_split=15,
                       random_state=42)

In [61]:
predictions = model.predict(X_test)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [62]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test,
    predictions
)

print(
    "Accuracy:",
    round(accuracy * 100, 2),
    "%"
)

Accuracy: 95.0 %

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [63]:
%cd /content/curriculum_industry_skill_alignment

!feast materialize \
    2025-01-01T00:00:00 \
    2025-01-02T00:00:00

/content/curriculum_industry_skill_alignment
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
Materializing 1 feature views from 2025-01-01 00:00:00+00:00 to 2025-01-02 00:00:00+00:00 into the sqlite online store.

curriculum_features:

In [64]:
online_features = store.get_online_features(
    features=feature_service,
    entity_rows=[
        {
            "student_id": 25
        }
    ]
).to_dict()

In [65]:
print(online_features)

{'student_id': [25], 'is_placed': [0], 'semester': [7], 'programming': [9.0], 'gender_encoded': [0], 'skill_count': [3], 'cgpa': [7.059999942779541]}

In [66]:
online_df = pd.DataFrame(
    online_features
)

display(online_df)

,student_id,is_placed,semester,programming,gender_encoded,skill_count,cgpa
0,25,0,7,9.0,0,3,7.06

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [67]:
final_model = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

final_model.fit(X, y)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

DecisionTreeClassifier(max_depth=4, random_state=42)

In [68]:
X_online = online_df[
    feature_columns
]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [69]:
prediction = final_model.predict(
    X_online
)

print(
    "Predicted survival:",
    prediction[0]
)

Predicted survival: 0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [70]:
online_features = store.get_online_features(
    features=feature_service,
    entity_rows=[
        {"student_id": 10},
        {"student_id": 20},
        {"student_id": 30},
        {"student_id": 40}
    ]
).to_dict()


online_df = pd.DataFrame(
    online_features
)


display(online_df)

,student_id,is_placed,semester,programming,gender_encoded,skill_count,cgpa
0,10,0,7,10.0,1,4,6.73
1,20,0,7,7.0,0,5,8.50
2,30,0,8,4.0,0,3,6.96
3,40,0,7,10.0,0,3,9.32

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [71]:
online_df["predicted_industry_readiness"] = (
    final_model.predict(
        online_df[feature_columns]
    )
)


display(
    online_df[
        [
            "student_id",
            "predicted_industry_readiness"
        ]
    ]
)

   student_id  predicted_industry_readiness
0          10                             0
1          20                             0
2          30                             0
3          40                             0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)